### ISSUE TITLE
Bug that popped up today

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#100]
11:32:51.164 //(bug) BACKWARDS usage: numbers(1, -1)! 
11:32:51.165 //(bug) produce_coredump called with pointer (nil) 
11:32:51.165 //(bug) Error detected: Producing coredump 4 of 10. 

Those timestamps are from my log, so they are MST. Nothing bad happened when this occurred, no crash. But might be something to look into. Ozy says he saw it at least twice today.

**Comment by dmhenderson76** [comment]
Just happened again.  No idea what's wrong with this mob but something is definitely screwy.  Only prog is a "say on death" death_prog that should not cause this:

/(world) Mob 4125 trying illegal n in MOBProg. 
//(world) Mob 4125 trying illegal n in MOBProg. 
//(world) Mob 4125 trying illegal n in MOBProg. 
//(world) Mob 4125 trying illegal n in MOBProg. 
//(world) Mob 4125 trying illegal n in MOBProg. 

Z:159 R:29358 I:1> 
//(world) translate_value: Mob: 4125 invalid target in mobprog 

Z:159 R:29358 I:1> 
//(bug) BACKWARDS usage: numbers(1, -1)! 
//(bug) produce_coredump called with pointer (nil) 
//(bug) Error detected: Producing coredump 5 of 10.

**Comment by TehDreadPirateRoberts** [comment]
I think we fixed the error that was in a zone file. Haven't seen it since.
