### ISSUE TITLE
aarand_prog is broken

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#102]
Intended functionality:  aarand (vs rand_prog) is supposed to work even when there are not any players in the zone with the mob.

Current functionality: aarand only fires when players are in the zone with the mob.  This has been tested using a mob that gates to its target when the target is no longer in the room.  The prog only fires when the player is in the zone with the mob in question.  Since then, tested with a few other mobs and confirmed it is not working as intended.

Not sure what broke it.

Desired behavior:  aarand_prog should fire regardless of whether players are in the zone or not.  I wonder if this has anything to do with the changes to $r

**Comment by jhhudso** [comment]
Fixed.
