### ISSUE TITLE
Urgent:  rand_prog is not working now

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#103]
May be a result of the recent aarand_prog changes.  Now rand_progs do not fire at all.  Tested with multiple mobs with arg set to 100.  Rand_prog is not working at all (anywhere).

**Comment by jhhudso** [comment]
I tested and could not reproduce confirm. Please paste proof or send steps to reproduce on a blank mob.

**Comment by dmhenderson76** [comment]
Game crashed, it's working now.  No idea why it stopped.
