### ISSUE TITLE
Pass not crumbling away when in backpack

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#107]
https://github.com/DarkCastleMUD/DarkCastle/blob/e8e649ae74871af06f3ca6c2ed565ed93051f42f/src/obj_proc.cpp#L2305

I *think* that the pass not expiring is related to that the check is only checking if the char as the obj on him vs using something like: !search_char_for_item(i, real_object(30097)). That search_char_for_item is how Jeff checks to allow you in, which is why you can still get in when the pass is in your backpack.

I think this is why anyway...

**Comment by jhhudso** [comment]
fixed.
