### ISSUE TITLE
Issues with MPADDLAG command

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#122]
I can't give a specific example here because I went back and took MPADDLAG lines out of all the burial grounds mob progs, but there are instances where a mob has a powerful attack in their arsenal that you don't want them A) spamming every round and/or you want them to take a breather for a few rounds after it goes off to give the PC party a chance to recover/react (ex:  You don't want a mob casting a super AoE Solar gate every round).  It would be nice if the MPADDLAG command worked on mobs so that they simply could not issue commands for the duration of the lag spell.  That said, we also don't want mobs "stacking" commands while in lag like players do because it will limit their ability to react to player actions - rather, this command (when used on a mob) should basically take away their command parser for a set duration, allowing them to resume when the combat timer is up.  

The workaround right now is to set the %chance for the prog in-question to fire to a low chance and then just hope they don't use it in quick succession, but that isn't a real solution.

**Comment by dmhenderson76** [comment]
MPADDLAG does not work with the "MPAT" command either.  Example, a mob hurls a player out of a room slamming them into the wall.  The mob then attempts to "stun" (lag) the player for a few seconds before they can scramble to their feet and re-enter combat.  Currently, MPAT <target> MPADDLAG does not work - not sure if this is intended behavior or not.

**Comment by jhhudso** [comment]
I've resolved this with MPPAUSE command. It now has an optional all argument as in MPPAUSE all #. In this scenario it will pause all mob programs within a mob for # seconds.
