### ISSUE TITLE
***URGENT*** Burial Grounds Daypass check is kicking players out of House of Horrors

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#123]
Reported by Jack - confirmed behavior with my mort and imm:

Burial Grounds zone range is 30000-30099
House of Horrors zone range is 29300-29399

There's a mechanic where if you enter the burial grounds somehow without a daypass, there's a prog object that will boot you from the zone back to the entrance.  Prog object# is 30096.

Everything was fine up until recently(?) - Jack attempted to go into House of Horrors for hunt targets and the game somehow performed the daypass check on him and booted him half a world away to the entrance of Burial Grounds.  I have no idea why the daypass checker is now looking at the wrong zone range but it is.

Thankfully, the teleport takes you to a safe room but it's not in a very safe place - especially for lower-level players.  I'm going to remove the entrance to HoH until this can be fixed.

**Comment by dmhenderson76** [comment]
Update - talking with Matt and he said the other day when a new zone was inserted for Demon Dryads/Tarin(?) that it changed zone numbering.  It's possible that's the cause.

**Comment by dmhenderson76** [comment]
Fixed by Julian.  Closing.

**Comment by dmhenderson76** [comment]
Issue persists.  Forgot that prog won't fire on imms - only works on morts.  Checked with my mort and it does indeed still trans you back to burial grounds.

**Comment by TehDreadPirateRoberts** [comment]
Looks like this is coming from line 2373 in obj_proc.cpp.

Also, 1 more thing, before the line which is currently 2386:        
move_char(i, real_room(30000));

can you please add an act() with:
You feel dizzy and fade out of existence.

Then after that line can you force the character to look? Otherwise it transfers them and they don't know which room they are in.

**Comment by jhhudso** [comment]
I fixed the 2373 line, recompiled and rebooted. I'll add the requested act()s after work.

**Comment by jhhudso** [comment]
ok additional messages, depending on level, added as well as forced look
