### ISSUE TITLE
Defensive Skills

### ISSUE THREAD

**Issue by Heaven1** [DarkCastleMUD/DarkCastle#131]
As far as i can tell from reading the source code it is better to have 2 defensive skills such as dodge and parry rather than one of them and shieldblock as you take damage while shield blocking but it doesnt provide any more of a chance for enemies to miss you (or have the damage reduced) than the 2 defensive skills. This seems wrong, you are sacrificing damage using a shield. IMO that sacrifice should provide a more of a bonus.

If im correct about all of this (im not certain) than i suggest a secondary shield skill on top of the existing one which boosts the chance to block damage. 

Or perhaps alternatively, provides melee mitigation when using a shield.

**Comment by TehDreadPirateRoberts** [comment]
I personally use a shield quite often when fighting big mobs and really like how it works.
Instead of coding it to add melee mit, I just have found a shield that his a bonus to melee mit right on it...
