### ISSUE TITLE
redit extra

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#133]
Syntax: redit extra <keywords>
Use it once to create the desc with a new keyword(s).
Use it a second time with one of those keys to edit the description for it.

The above is what is shows for redit extra. I have tried a bunch of times to create a new desc with multiple keywords but it doesn't seem to be working. If you try to use it a second time with one of the keywords to edit the description, it creates a new desc with the same keyword.

**Comment by jhhudso** [comment]
fixed and added redit extra delete <keyword> option as well.
