### ISSUE TITLE
suggestion: show dam type and wear locations on identify

### ISSUE THREAD

**Issue by Heaven1** [DarkCastleMUD/DarkCastle#134]
it would be nice if identify showed the damage type dealt for weapons and wear locations

**Comment by jhhudso** [comment]
> identify sword
Object 'sword troy xiphos', Item type: WEAPON
Item is: ANY-CLASS  NoBits 
Worn on: TAKE WIELD 
Worn by: Medium races 
Weight: 15, Value: 100000, Level: 35
Damage Dice are '2D9'
Can affect you as:
    Affects : HIT -N- DAM By 3
    Affects : DISPEL EVIL By 3

It does have wear locations already. See "Worn on: TAKE WEILD". Let me know if you mean something else.

I will add damage type.

**Comment by jhhudso** [comment]
Damage type added.

identify sword
>Object 'sword troy xiphos', Item type: WEAPON
Item is: ANY-CLASS  NoBits 
Worn on: TAKE WIELD 
Worn by: Medium races 
Weight: 15, Value: 100000, Level: 35
Damage Dice are '2D9'
Damage type: slash
Can affect you as:
    Affects : HIT -N- DAM By 3
    Affects : DISPEL EVIL By 3
