### ISSUE TITLE
object prog causing a glitch

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#135]
When you use the keyword for the object prog for the thief quest cloak, you are also affected by the bard set (at least it shows up in the list of spells affecting you...)

_Spell : 'Troubadour's Finery' (1219)
     Modifies NONE by 0 points
     Expires in  23 hours
Spell : 'shadowslip' (119)
     Modifies NONE by 987 points
     Expires in   5 hours_

_Object: cape shadows vystir thief quest   Vnum: 27980.

1>speech_prog umbra
if isworn($n)
  mpechoat $n You utter the command word and are partially obscured in a swirl of shadow...
  mpecharound $n mutters a few words, and blurs into a swirl of shadow.
MPBESTOW $n shadowslip 6 24
endif_

**Comment by jhhudso** [comment]
Fixed.
