### ISSUE TITLE
warrior quest, 2 issues

### ISSUE THREAD

**Issue by Heaven1** [DarkCastleMUD/DarkCastle#137]
iv completed the quest skill with one character, but my two other warriors have two separate issues with two separate quest skill steps for warrior:

1)  i finished all of endris's fetch steps and told hydel im worthy witch each weapon. hydrel then said:
Hydel says 'Come back in a bit for your diploma... I have to prepare it first.'
so i left and came back later, to nothing. a full day has passed and still havent got it complete. 

on the warrior who actually finished the quest, instead of leaving when he told me come back... i stood there and he gave this message which i presume is the next step in the quest:
Hydel takes a seat and begins scribing something on a roll of parchment.
then when i left and came back i received the quest.

so i would assume the problem is leaving before he starts 'scribing'. considering he specifically instructed you to leave, i feel this a huge bug. regardless, one of my warriors (Dyniac) is not able to progress because of it. he is unable to restart the quest nor complete it.

2) one of my warriors has completed two of endris's fetches(whip and sting), but the other 2 quest items will not load. the target mobs i confirmed were loaded before requesting to fetch. iv tried repeatedly and they will not load. i suspect it is because there is another player(a bot who is always online) who has the quest items in their inventory thus preventing them from loading again thus denying me advancement indefinitely.

**Comment by Heaven1** [comment]
a crash reset quest progress.

**Comment by jhhudso** [comment]
I ended opening a duplicate issue for this one which I'll work from until it's permanently fixed even though it no longer affects you personally. See https://github.com/DarkCastleMUD/DarkCastle/issues/139
