### ISSUE TITLE
Set hunger & thirst to 0? upon death

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#142]
A request has been made to have hunger and thirst reset after you die. This kinda makes sense to me, as you would no longer be full if you were dead.

**Comment by dmhenderson76** [comment]
Yeah this has always been goofy.  Agreed.

**Comment by TehDreadPirateRoberts** [comment]
Set hunger and thirst to 0 upon death so if you need to quaff after dying you can.
