### ISSUE TITLE
"You feel more competent..." message bug

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#148]
https://github.com/DarkCastleMUD/DarkCastle/blob/883f5c027d9c23ab3a9141f0bc29ecfa69b6e5e6/src/guild.cpp#L1168

The "maximum" that is being listed here does not take into account the changes to the maximum based on race.

Example:
I am a troll warrior and the max my stinging can go is 87 but I get the following message:
_You feel more competent in your stinging_weapons ability. It increased to 87 out of 90._

From score sheet:
 _Stinging                        superb  87/ 45/ 87             Weapons_

**Comment by jhhudso** [comment]
Fixed.
