### ISSUE TITLE
Players are using the consignment broker for infinite storage

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#159]
Players can list items to their alts and have the consignment broker hold them indefinitely which undermines the purpose of vault size upgrades.  (Just go to consignment with your imm and do a "vend list all" and you'll see what I mean).

**Comment by dmhenderson76** [comment]
Suggestion: Bring back listing fees.  There's no way to prevent this otherwise.  Just charge the broker fee up-front and set the minimum listing fee to ~500k or so in order to make this approach less economical than just buying vault space.

**Comment by jhhudso** [comment]
I'll bring back listing fees only for private sales

**Comment by dmhenderson76** [comment]
Good solution
