### ISSUE TITLE
Problems with Obj# 30097

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#161]
Intended object behavior:
* Only 4 passes can exist at one time - Far Reach Undertaker should refuse money/issue no further passes after 4 are in existence.
* When passes expire, they disintegrate
* Players should be able to purchase new passes once there are >4 in the world

Currently happening:
* Passes generate as intended upon payment
* Passes do decay after 2 hours of in-game time
* Passes are NOT restricted to 4 maximum (bug)
* Purchase of repeated passes after the first set expires causes instability and the game crashes.  Not 100% but approaches 100% by about the 4th set (bug) - under investigation

**Comment by TehDreadPirateRoberts** [comment]
Passes do decay after 2 hours of in-game time
- This was fixed a while back
Passes are NOT restricted to 4 maximum (bug)
- I added a check (if amtitems(30097) >= 4) into the mprog for mob 9999 command 4 so now no more than 4 passes can be purchased
Purchase of repeated passes after the first set expires causes instability and the game crashes. Not 100% but approaches 100% by about the 4th set (bug) - under investigation
- This was fixed a while back
