### ISSUE TITLE
Tried email and in-game tells but I just dup'ed an entire set of EQ

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#17]
...including godload, quest gear and !trade stuff.  If someone could log in and pop on over to my chall, that'd be great.  I'm sitting here guarding the whole mess of it but I don't want to touch it.  I went afk to make dinner resting in my chall.  While I was gone, link went idle and disconnected.  Logged back in, reconnected and noticed some...valuable stuff on the ground and pretty quickly realized what happened.  Everything I was carrying is now resting on the ground beneath me (I didn't die, my xp is where it was when I left and I still have all my original gear).  Don't really want to touch anything as I am going to assume this is not "intended behavior".  

Side note: Found a typo in the long desc of the paladin quest gauntlets though - which no one has likely ever seen before.

Also my clan guard is pretty shitty so you might want to get here sooner rather than later.

**Comment by jhhudso** [comment]
There was a crash with the version of the game that was running, this inadvertently the to revert to a previous version. Unfortunately that previous version had a obj dupe bug in it. So I dont think (hopefully) this bug still exists now that I've rebooted but I do need to fix the cause of the crashing bug.
