### ISSUE TITLE
Bug:  Starting a hunt for over 50 items causes it to glitch out and start handing out empty prizes after ~54 or so

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#179]
What it says on the tin.  In "huntstart", the game states that you can run a hunt for up to 60 items for a maximum of 60 minutes however, if you run a hunt for more than 50 items, the game stops handing out rewards shortly after you cross 50.  Either A) fix this so hunts can go to 60 items and still pass out items or B) drop the maximum number of items to 50.

**Comment by TehDreadPirateRoberts** [comment]
Maybe change the 50 to a 60 in lines 1707 and 1713 of wizard.cpp? I tried to test this on my own computer but was unable to do so, I think I am missing some files for huntitems.

**Comment by TehDreadPirateRoberts** [comment]
Lowered hunt limit to 50 since huntitems.txt only has 50 items in it (this is what was causing the problem).
