### ISSUE TITLE
Reduce cooldown on failed barbarian skills

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#186]
...they are WAY too long:

Both Crazed Assault and Bloodfury have incredibly long cooldowns on skill failure.  Perhaps make the downtime 1-2 ticks on failure?

**Comment by TehDreadPirateRoberts** [comment]
I think crazed assault looks fine. Once you are max skill it will be 0 for cooldown on failure.
Bloody fury though could be adjusted maybe to be similar to crazed assault (currently would be 20 for duration on failure).
And maybe change it from 26 on success to 24 (1 day).
Crazed assault should also maybe be changed from skill_increas_hard to skill_increase_easy.

**Comment by jhhudso** [comment]
I looked at the failure and success cooldowns for warrior and barbarian skills and have changed failure cooldown to 1.
