### ISSUE TITLE
Consecrate and Desecrate are not dealing damage to high level mobs due to code issue

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#187]
line 2544 on nanny.cpp
"if (GET_LEVEL(tmp_ch) >= IMMORTAL)"

Needs an additional check to make sure the target is a PC as well as above level 100.  As it is currently written, mobs above level 101 will not take damage from the skills.

**Comment by TehDreadPirateRoberts** [comment]
Jared fixed.
https://github.com/DarkCastleMUD/DarkCastle/commit/7f3d27e950b6b0b6b1e015230a3d565e035783e2
