### ISSUE TITLE
Max this boot counts connections even if they are at CONFIRM_NEW_NAME

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#188]
[:]===================================[:]
|/|      Denizens of Dark Castle      |/|
[:]===================================[:]

[   Divinity  ] Westley - as you wish.  (WizInvis 106) 

    Visible Players Connected:   0
    Visible Immortals Connected: 1
    **(Max this boot is 1)**

Z:0 R:29 I:106> sock
  7 : 68.150.96.190   | Asdfafda         |CONFIRM_NEW_NAME     |14
  6 : 68.150.96.190   | Westley          |PLAYING              |0

There are 2 connections.

Z:0 R:29 I:106> who
[:]===================================[:]
|/|      Denizens of Dark Castle      |/|
[:]===================================[:]

[   Divinity  ] Westley - as you wish.  (WizInvis 106) 

    Visible Players Connected:   0
    Visible Immortals Connected: 1
    **(Max this boot is 2)**

**Comment by jhhudso** [comment]
fixed
