### ISSUE TITLE
Orro's Wand of Wonder obj# 3124 not functioning as intended

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#190]
Wand has 5 charges of full heal.  When depleted, the wand is supposed to recharge using:
Qty (1) of 27904 
Qty (2) of 27903
Qty (1) of 17399

When "Push button" is entered, the wand should consume the ingredients and restore all 5 charges of heal.
Currently, nothing happens and "push button" doesn't seem to do anything at all.

There should be an error message when:
1) button is pushed but required ingredients are not in inventory
2) button is pushed but wand is already full

There's also supposed to be a "display" you can examine on the wand to see how many charges are left.  That doesn't seem to be working either.

**Comment by TehDreadPirateRoberts** [comment]
If you try to recharge it when it is already full... maybe the players fault for being a dunder head? If you really think it needs this let me know and I can try to figure how to write this on my dev server (just a little tough without some obj files..).
As for the other concerns, I think they are addressed below:

Changed the desc from:
   Printed in incredibly small text upon the wand are a set of instructions:
Hello and congratulations on your purchase of a Wand of Wonder(tm) This wand
contains 5 charges of Full Heal.  Examine the (display) to see how many charges
it has left.  If your wand runs out of charges, simply collect 2 deep blue
potions, 1 deep red vial and a shimmering diamond and push the recharge
(button) and it'll be good as new!  We sincerely hope you enjoy your purchase!
-Management
To:
   Printed in incredibly small text upon the wand are a set of instructions:
Hello and congratulations on your purchase of a Wand of Wonder(tm).  This wand
comes with 5 charges of Full Heal.  Identify it to see how many charges remain.
If your wand runs out of charges, simply collect 2 deep blue potions, 1 deep
red vial and a shimmering diamond.  Then hold the wand and say "recharge" and
it'll be good as new!  We sincerely home you enjoy your purchase!
-Management

**Comment by jhhudso** [comment]
#3124
wand wonder orro~
Orro's Wand of Wonder~
A wondrous looking wand enscribed "Orro" sits here humming quietly.~
Fixed.~
3 83 16385 1
70 5 5 78 50
3 100000 13
E
wand wonder orro~
   Printed in incredibly small text upon the wand are a set of instructions:
Hello and congratulations on your purchase of a Wand of Wonder(tm).  This wand
comes with 5 charges of Full Heal.  Identify it to see how many charges remain.
If your wand runs out of charges, simply collect 2 deep blue potions, 1 deep
red vial and a shimmering diamond.  Then hold the wand and say "recharge" and
it'll be good as new!  We sincerely home you enjoy your purchase!
-Management
~
S

**Comment by TehDreadPirateRoberts** [comment]
@jhhudso  I thought I fixed it with the above change to the description, did I not?

**Comment by jhhudso** [comment]
fixed in latest commits:
* added push button in addition to existing say recharge
* it won't consume components if wand is full of charges now
* when you're lacking components it will tell you which components you're missing
