### ISSUE TITLE
Warnings and ErrorHandler::underrun on a lot of rooms in clean install

### ISSUE THREAD

**Issue by fippls** [DarkCastleMUD/DarkCastle#196]
Hi!

Built from scratch and started a clean server, getting these errors:

Thu Aug  4 20:29:03 2022 :: Booting individual world files
Reading Room: $B$4Do not edit room 257$R, 256
fread_int: Bad value - < 0 on positive only num
Reading Room: $B$4Do not edit room 257$R, 256
fread_int: Bad value - < 0 on positive only num
Reading Room: $B$4Do not edit room 257$R, 258
fread_int: Bad value - < 0 on positive only num
Reading Room: $4$BDo not edit room 259$R, 259
fread_int: Bad value - < 0 on positive only num
Reading Room: $4$BDo not edit room 259$R, 259
fread_int: Bad value - < 0 on positive only num
Reading Room: $B$4End of Platsmith and Special Proc Range$R, 299
fread_int: Bad value - < 0 on positive only num
Reading Room: A tunnel below the north wall of Sorpigal, 3028
fread_int: Bad value - < 0 on positive only num
Reading Room: Magiks R Us, 3033
fread_int: Bad value - < 0 on positive only num
Reading Room: The Meta Shop, 3059
fread_int: Bad value - < 0 on positive only num
Reading Room: Arnold's House of Authentic Austrian Arrows, 3060
fread_int: Bad value - < 0 on positive only num
Reading Room: The Morgue, 3096
fread_int: Bad value - < 0 on positive only num
Thu Aug  4 20:29:03 2022 :: World Boot done.

Then after creating a character and after going 2n from the DC++ reception area, server crashes with the following error each time:  **terminate called after throwing an instance of 'ErrorHandler::underrun'**

There are several other rooms that throw underrun as well, for example the paladin guild.

**Comment by jhhudso** [comment]
Ok I fixed the bad room number values causing those warnings. I also added the mud school area and guild halls.

**Comment by fippls** [comment]
Many thanks! Question: is it possible to add more areas from the original DC instance?
