### ISSUE TITLE
zedit edit arg3 when type is p returns real number vs virt number

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#203]
I think this is in lines 601 to 612 of wiz_102.cpp.
When you have a zone line that is type p and you zedit edit arg3 the real number of the object will echo to the char instead of the virtual number.

Z:58 R:7238 I:0> zedit edit 26 3 7210
Arg 3 set to 2220.

**Comment by jhhudso** [comment]
fixed
