### ISSUE TITLE
Command "look out" not working after you enter a portal

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#215]
https://github.com/DarkCastleMUD/DarkCastle/blame/d9b6da202d97bdf39f3d4c464b2c6e9b8653cf18/src/info.cpp#L1679

Eg. obj 21399 loads in room 29090. Enter dock and then try "look out" and it just says, "Nothing much to see there."

**Comment by jhhudso** [comment]
Fixed in 15eaee6c691b049cce803dfa8daa8531cccb3650
