### ISSUE TITLE
Problems with zedit

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#216]
Several of the commands in in do_zedit are not working:
zedit flags - if you use any of the args it can turn on the flags, but it will not remove them if they are on or once you turn the flags on.
_Z:50 R:5900 I:0 M:0 O:> zedit flags noclaim
Noclaim turned on.

Z:50 R:5900 I:0 M:0 O:> zedit flags noclaim
Noclaim turned on._

zedit lifetime - for some reason this is wanting 3 args, but if you use zedit lifetime # # (any #s), depending on the zone you are in the lifetime will be set but you cannot choose what it is set to and what it gets set to depends on the zone you are in.
_Zone 50's lifetime changed to 153.
Zone 129's lifetime changed to 251._

zedit name - only accepts first word you changed to name to in the arg
_Z:129 R:21300 I:0 M:0 O:> zedit name Just Testing
Zone 129's name changed to 'Just'._

zedit add - if i use a number or 'new' as the arg, it doesn't work
_Z:129 R:21300 I:0 M:0 O:> zedit add new
You must state either 'new' or the insertion point which must be between 0 and 252.
'new' is not valid.

Z:129 R:21300 I:0 M:0 O:> zedit add 220
You must state either 'new' or the insertion point which must be between 0 and 252.
'220' is not valid._

That is all I tested, looks like there are problems with most, if not all of the commands. Let me know if you would like me to test any more of the commands.

**Comment by TehDreadPirateRoberts** [comment]
zedit edit is also not working. Always returns: _That is not a valid command number._

**Comment by TehDreadPirateRoberts** [comment]
The zedit command followed by a number will crash the mud. Eg. zedit 0

**Comment by jhhudso** [comment]
fixed with latest commits.
