### ISSUE TITLE
Maxcheck listing the zone as 10000

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#218]
Reset 16 in zone 10000 has LESS resets than max in world.
Reset 55 in zone 10000 has LESS resets than max in world.
Reset 64 in zone 10000 has LESS resets than max in world.
Reset 67 in zone 10000 has LESS resets than max in world.
Reset 76 in zone 10000 has LESS resets than max in world.
Reset 6 in zone 10000 has LESS resets than max in world.
Reset 10 in zone 10000 has LESS resets than max in world.
Reset 16 in zone 10000 has LESS resets than max in world.
Reset 22 in zone 10000 has LESS resets than max in world.
Reset 37 in zone 10000 has LESS resets than max in world.
Reset 91 in zone 10000 has LESS resets than max in world.

**Comment by jhhudso** [comment]
fixed in latest commit.
