### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#219]
oedit <vnum> affect 3 <num> without another arg at the end will crash the mud.
Technically it should be oedit <vnum> affect 3 <num> <skillnum>, but I had thought that previously if you leave out the <skillnum> it listed the skills you could put in. Instead it is currently just crashing the game.

Z:1 R:29 I:0 M:0 O:607> oe aff list
Character Affects:
------------------
 1) HIT -N- DAM(26) by 7.
 2) CURE LIGHT(56) by 100.

Z:1 R:29 I:0 M:0 O:607> oe aff
Syntax:  oedit [item_num] affects [affectnumber] [value]
The field must be one of the following:
               new            delete              list            1spell
           2amount            3skill

Z:1 R:29 I:0 M:0 O:607> oe aff 3 1
    
[ ALERT ] - Socket got disconnected.
            Reason: The remote host closed the connection
[ INFO ]  - Connection time: 00:00:46.365

**Comment by jhhudso** [comment]
fixed with latest commit.
