### ISSUE TITLE
Line can be removed - just echos a "3" to char

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#225]
https://github.com/DarkCastleMUD/DarkCastle/blob/70394a3c9d8d2ce51cb2dfab5dccdaf978ebc842/src/wiz_102.cpp#L778

Z:132 R:21920 I:0 M:0 O:21913> zedit edit 1 3 21902
Arg 3 set to 21902.
3
Z:132 R:21920 I:0 M:0 O:21913>

**Comment by jhhudso** [comment]
fixed in latest commit
