### ISSUE TITLE
Szrilodor pass is not reseting zone

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#226]
https://github.com/DarkCastleMUD/DarkCastle/blob/d56efa65f8ca51f7774d28520938a199907fdd38/src/obj_proc.cpp#L2443C1-L2576C2

The Szrildor pass code is not working as intended. This is by no means a full explanation of the code, just a summary of what should happen.

When you purchase a pass from the undertaker by giving him 10,000,000 gold it is supposed to:
1. check if there are already any passes - if any exists do nothing
2. if none exists and this is the first pass - clear the zone (zone 164) and repop/reset the zone (zone 164)

Currently, when the first pass is purchased it looks like most of the zone gets cleared (but I can still find some of the mobs if I run the command 'find m szrildor') - and then the zone does not repop.

**Comment by jhhudso** [comment]
fixed in latest commit
