### ISSUE TITLE
[BUG] Vault search takes approx 10 seconds

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#232]
**Describe the bug**
'vault search' used to be almost instant but now it will lag you for 10 seconds

**To Reproduce**
1. vault search keyword test
2. vault search level 1

**Expected behavior**
Fast response listing results of search parameters

**Comment by jhhudso** [comment]
vault search as mortal or immortal?

**Comment by jhhudso** [comment]
fixed.
