### ISSUE TITLE
vault get all.<obj> not working

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#233]
https://github.com/DarkCastleMUD/DarkCastle/blame/857dce5ceb2241066bb9d870b4e80d0eedfe59ed/src/vault.cpp#L1501

I am not 100% sure if this is the line that is causing this, but vault get all.<obj> is not working. It only gets the first item found with that name from the vault, not all of them.

**Comment by jhhudso** [comment]
fixed in latest commit
