### ISSUE TITLE
[BUG] ACID BLAST on Morcallen's Magickal Barrier not working

### ISSUE THREAD

**Issue by jhhudso** [DarkCastleMUD/DarkCastle#234]
Monk Hondo reports that ACID BLAST is not going off from Morcallen's Magickal Barrier.

Z:116 R:18340 I:0 M:0 O:> ident v30000
Short description: Morcallen's Magickal Barrier
Keywords: 'shield barrier morcallen magickal relic'
Item type: ARMOR
Extra flags: GLOWING ANTI-EVIL WARRIOR PALADIN MONK 
More flags: UNIQUE NO_TRADE NO_LOCATE 
Owner: 
Worn on: TAKE SHIELD HOLD 
Worn by: Any race 
Level: 59
Weight: 10
Value: 3000000
AC-apply is 50 (50)     Resistance to damage is 0
Can affect you as:
    Affects : ALL SAVES By 5 (5)
    Affects : shield_block By 15 (15)
    Affects : MELEE MITIGATION By 4 (4)
    Affects : HIT -N- DAM By 6 (6)
    Affects : ACID BLAST By 7 (7)

**Comment by TehDreadPirateRoberts** [comment]
@jhhudso The acid blast only works when item is "held" - not if worn as shield. I just tested it and it is working as intended.
