### ISSUE TITLE
[BUG] Vault myaccess  VERY slow, locks for 10-20 seconds

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#235]
**Describe the bug**
When you type _vault myaccess_ it locks up for 10-20 second before you see the response

**To Reproduce**
1. Type vault myaccess

**Expected behavior**
Response should be very fast

**(please complete the following information):**
 - OS: OSX and Windows
 - MUD client: MUDlet and tintin++

**Additional context**

**Comment by tenaz123** [comment]
This locks up the whole mud by the way, not just the person using the command.

**Comment by TehDreadPirateRoberts** [comment]
Also lags up the same way when using vault search world

**Comment by jhhudso** [comment]
fixed in latest commit
