### ISSUE TITLE
[BUG] rsave is not saving the files

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#249]
**Describe the bug**
When you use the command 'rsave' the room files are not being save. After a restart the changes will not be saved (although you are getting a message back that confirms that the changes were saved.

**To Reproduce**
1. Use redit and change something in a room
2. rsave

**Expected behavior**
Room files are saved when you use the command.

**Screenshots**
The following shows up in terminal:

unknown:0:QFile::copy: Empty or null file name
Thu Nov 21 17:25:46 2024 :32: Unable to copy  to world/03001-3099.txt/%2.last.
unknown:0:"Unable to open world file '"

**(please complete the following information):**
 - OS: openSUSE Tumbleweed
 - MUD client tintin++ & Mudlet
- Version: v0.1-1572-g7e8e7608 Build time: 2024-11-04 14:44:03

**Comment by jhhudso** [comment]
fixed in latest stable and master commits
