### ISSUE TITLE
Grim Rockcrusher - the loneliest platinum vendor in Dark Castle

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#26]
So without getting into any other GL (yet)... can we talk about Grim Rockcrusher? It is like someone took what should be good (maybe an iPhone), decided to replicate it overseas and call it the MiPhone and advertise it as something worth purchasing. 

1 ) Duskbane, the Tainted Dagger 1d4, Two-handed, hit -n- dam by 2, 
    dispel magic by 12, curse by 5, age by -10, sex by 1, costing 6900 coins.

**What the fuck is this?? Has he ever sold one?? I struggle to see the logic behind this ever being considered an item someone would buy. Unless there is a story behind someone requesting an item and this is a big middle finger to the request, why bother with this item?**

2 ) King Baltanerous' Dread Pike 3d18, Two-handed, hit -n- dam by 7, 
    fear by 8, paralyze by 3, sense life by 100, costing 4500 coins.

**Ain't nobody got time for that.**

3 ) Grief-Forge, Hammer of the East 7d7, Two-handed, hitroll by 9, 
    damroll by 7, harm by 12, dispel magic by 5, costing 6500 coins.

**I mean, I guess it has dispel on it...**

4 ) Coar Fist's Bow of Legend hit -n- dam by 8, mana regen by 5, str by 2, 
    armor by -30, costing 2800 coins.

** The bows are the ONLY thing worth buying here. Well... except archery. **

5 ) the Centaurs' Hundred-League Bow hitroll by 10, damroll by 7, move by 50, 
    farsight by 100, costing 3100 coins.

So I haven't yet thought of suggestions for improvements, and I have a tee time shortly so I gotta bounce. But feel free to weigh in with ideas for changes to the items.

Alternatively we could just spend time adjusting other items of more importance and put these on the ignore list. Which might be the way to go.

**Comment by bdunavant** [comment]
This is not a code issue, and equipment is not stored in this repository.

Please discuss this on the Dark Castle forum or some other location appropriate for the content.
