### ISSUE TITLE
Crash bug:  "clear" command in zone 161 caused instant crash

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#28]
Was told to log it here.

**Comment by mcinelli61** [comment]
I suggest that he log it here so you would be aware to check the core dump.
We had a second crash later after an delete exit command.

**Comment by jhhudso** [comment]
Fixed

**Comment by dmhenderson76** [comment]
Did it again today.  Cleared zone 161, repopped.  Mobs didn't repop and actually had a second or two to move around but then the game crashed.
