### ISSUE TITLE
Brownie exchange for token

### ISSUE THREAD

**Issue by kupoholio** [DarkCastleMUD/DarkCastle#32]
Wonder if we can trade in brownie points for tokens?

**Comment by dmhenderson76** [comment]
Seconding this.  Not sure why they are excluded from the exchange vendor.

Edit:  Changing my response on this.  This can't happen because of the blue bull.

**Comment by jhhudso** [comment]
Closing this since you can now get 2 cloverleaf tokens from eddie for the cost of 1 brownie
