### ISSUE TITLE
Related to issue #28 - clearing and repopping zone 161 crashed game

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#35]
Behavior was little different than before.  Made some zonefile edits (just changing where mobs spawn), cleared zone, repopped.  Both commands went through, however no mobs loaded in the zone.  I had a few seconds to move around the zone after repop command was issued and then the game crashed.

Would have reopened the closed issue but didn't see a way to do that.

Crash happened at approx. 10:15EST

**Comment by dmhenderson76** [comment]
Happened again.  Cleared zone 161 at ~3:15PM EST and game immediately crashed (no load command this time)

**Comment by jhhudso** [comment]
fixed for now or at least I made it so it wont crash anymore
