### ISSUE TITLE
Vault bug - Moses

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#38]
His max storage has somehow gone negative and removing items from the vault causes them to go further into the negative.  This is...not good:

**Partial log follows:**

> Lost the full log but here are some short sections from what I am seeing:

            Your vault is at -186 of 640 maximum pounds and contains:

            dragonscale leggings   [Excellent] Lvl: 55

            dragonscale sleeves   [Excellent] Lvl: 55

            a dragon's claws   [Excellent] Lvl: 55
            a dragon's skull   [Excellent] Lvl: 55
            .........

            Remove a bunch of dragon stuff from vault....

             

            Your vault is at -227 of 640 maximum pounds and contains:

            dragonscale sleeves   [Excellent] Lvl: 55

            a suit of granite platemail   [Good] Lvl: 55
            the Plate of Illusion   [Excellent] Lvl: 1
            .........

Each time I remove something it goes more negative and I cannot place anything back in the vault. 

        vault put dragon

You can't seem to stuff a blue dragon scale in the vault.  Its too big!

**Comment by dmhenderson76** [comment]
Others are reporting this now too.  Issue seems to be tied to unique items in vaults.  Even if player does not have a duplicate unique item, game will not let them remove some(all?) uniques from vaults however, other players can simply hand the item to them with no problem.  Several players have reported similar issues in the past 3-4 days.

**Comment by jhhudso** [comment]
Restarting the MUD fixed the issue with Moses' vault but the underlying bug remains. If it happens again can you let me know exactly what item starts the issue. As for the possible UNIQUE item aspect of this bug, I need a specific example of an item that cannot be retrieved from the vault due to UNIQUEness yet someone is able to give Moses that same UNIQUE item.

**Comment by dmhenderson76** [comment]
1) Not sure what item started it.  Elder might know.

2) Specific example: obj Vnum 22325 (Dragon claws).  He was unable to remove from vault, but was able to hand them to Moses with another char.

**Comment by dmhenderson76** [comment]
Vault bug resolved - will reopen if it resurfaces.
