### ISSUE TITLE
New Crash Bug #1 Mob VNUM 30098

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#39]
Prog throws an error: /(world) Improper MOBprog operator

Test port crashes after a while or when I attempt to purge the room he's in:
Prog follows:
:0 R:17 I:0> procedit list
Name: Mr Lynn Aloysius Belvedere  Vnum: 30098.
Short description: Mr. Belvedere
Long  description: A portly, immaculately dressed, mustachioed butler stands before you.

1>catch_prog 1
MPGOTO 30084
sa WESLEY MY BOY!
follow $n

2>rand_prog 10
say STREAKS ON THE CHINA
MPPAUSE 3
sa NEVER MATTERED BEFORE - WHO CARED
MPPAUSE 3
sa WHEN YOU DROP KICKED YOUR JACKET
MPPAUSE 3
sa AS YOU CAME THROGH THE DOOR 
MPPAUSE 3
sa NO ONE GLARED
MPPAUSE 3
sa BUT SOMETIMES THINGS GET TURNED AROUND AND NO ONE'S SPARED
MPPAUSE 3
sa ALL HANDS LOOK OUT BELOW
MPPAUSE 3
sa THERE'S A CHANGE TO THE STATUS QUO(oh)
MPPAUSE 3
sa GONNA NEED ALL THE HELP THAT WE CAN GET
MPPAUSE 3
sa ACCORDING TO OUR NEW ARRIVAL
MPPAUSE 3
sa LIFE IS MORE THAN MERE SURVIVAL
MPPAUSE 3
sa AND WE JUST MIGHT LIVE THE GOOD LIFE YET!
MPECHO Mr. Belevedere does a little dance with his feather duster.

3>act_prog disappears
sa WESLEY!  WHERE ARE YOU GOING?  COME BACK!
MPPAUSE 5
MPGOTO $n
fol $n

4>fight_prog 100
say NOW NOW, SETTLE DOWN WESLEY.
say LET ME MAKE YOU A NICE CUP O' TEA.
MPPEACE $n
MPPEACE Belvedere

5>greet_prog 100
if ispc($n)
MPSETTEMP $n target true
say AH WESLEY, THERE YOU ARE!
follow $n
endif

6>act_prog stop following
follow $n
SAy NO WESLEY, YOU CAN'T GO WITHOUT ME!

7>rand_prog 30
if numpcs() = 0
MPGOTO $n
MPECHO A yawning portal to the Belvedere dimension suddenly snaps into existence and Mr. Belvedere emerges.
MPECHO The portal closes behind him.
Say WESLEY!  YOU CANNOT ESCAPE ME!
endif

**Comment by dmhenderson76** [comment]
Figured this out.  The issue here is that I was treating mob "follow" like PC "follow".  A mob does not need to be told to refollow a player it is already following.  A mob will **always** follow a player (regardless of found/disband, etc) unless it is somehow prevented from doing so.  However, when a player (or mob) attempts to refollow a player it is already following, it will receive a "you stop following" message prior to refollowing.

The crash bug was caused by this:
6>act_prog **stop following**
**follow $n**
SAy NO WESLEY, YOU CAN'T GO WITHOUT ME!

So - "You stop following <x> - calls the above act_prog
This was causing an infinite loop where the mob would see "stop following" and then try to refollow which would cause "stop following" again ...ad infinitum

**Comment by jhhudso** [comment]
agreed but even without your change the bug is fixed as well
