### ISSUE TITLE
Crash bug (unknown) possibly triggered by purging Mob VNUM 30033 2:06AM EST

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#41]
>Ozymandias: it's set up correctly.  Probably just needs a reboot

>Z:161 R:30014 I:0> l
Szrildor Burial Path Light[9] <hills> [ no_mob no_track ]
(Guide) Elder the Gnome is here.
-Elder has: aura! frost! energy! flying!
Chop the Human [Arcana] is resting here.
Exits: north west south-closed east 

>Z:161 R:30014 I:0[goto jeff
At the Gates of the Szrildor Estate Light[3] <inside> [ no_track ]
a "For Sale" sign juts haphazardly from the marshy ground here.
A bored looking real estate agent lounges here.
-Jeff has: aura! 
Exits: north-closed 

>Z:161 R:30000 I:0> purge
You gesture...the room is filled with scorching flames!

>Z:161 R:30000 I:0> 
#SESSION '1' DIED.
#THERE'S NO ACTIVE SESSION NOW.

The interesting bit is that right before this, his mob prog which previously worked (command 7, line 15) started returning "huh".
Line is:

15: MPAT $n MPFORCE $n look
(force look after transfer)

After game rebooted, I went on the test port and tried it again.  Now the prog functions properly (multiple trips through it) and purging/repopping does not crash the game.

**Comment by jhhudso** [comment]
Unless you can reproduce it, I think with my latest changes these purge induced bugs should be fixed.
