### ISSUE TITLE
Szrildor progs

### ISSUE THREAD

**Issue by urizen-source** [DarkCastleMUD/DarkCastle#43]
Issue for adding Szrildor progs for Ozy.

* Added code for daypasses that limits the # of players in the zone to 4 -carrying daypasses-
* Anyone not carrying daypasses or exceeding 4 is extracted
* Also added MPIF check for numofobjsinworld that was needed for the logic for <secret> to not sell more than 4 daypasses

**Comment by dmhenderson76** [comment]
Hey please take the name of the questgiver out of bullet #3 :P 
Spoilers!

**Comment by dmhenderson76** [comment]
Started up the test port this evening and:

1. Even though the pass is flagged unique, quest-giver will hand you multiple passes.  Need to build a "if carries" check prior to doing anything else (I will do this).

2. Quest giver currently allows infinite passes in the world (needs to be fixed)

3. No pass timer exists (display time left) when examining the object.

4. Pass does not decay after 2 hours.  

5. Mort chars in zone after 2 hours are not removed (tied to above).
