### ISSUE TITLE
master branch has a bug causing crashes or corruption when players die to mobs

### ISSUE THREAD

**Issue by jhhudso** [DarkCastleMUD/DarkCastle#5]

**Comment by urizen-source** [comment]
Saw the fixes you did for this, great :)

**Comment by jhhudso** [comment]
I've fixed two bugs causing crashes (aborts) in master branch. One was act() after a player logs out was attempting to send messages to room -1 which caused the world[] class to throw an exception causing an abort. The other bug was with a mobprogram after a mob purges itself via MPPURGE $i. Both are fixed and testing on port 6666.
