### ISSUE TITLE
Locate object spells no longer finds corpses and PC portals

### ISSUE THREAD

**Issue by mcinelli61** [DarkCastleMUD/DarkCastle#50]
Since https://github.com/DarkCastleMUD/DarkCastle/commit/6ff759ae42950adfd174726cd791846676d0f067#diff-87b56e4ecbeb26b417f05dd5b64b2e7b was changed, locate object spell no longer finds cleric/mage portals or PC/NPC corpses. In both cases, these items have RNUM -1 and VNUM 0.

**Comment by urizen-source** [comment]
@jhhudso  fixed this yesterday with https://github.com/DarkCastleMUD/DarkCastle/commit/5c9f772d55e40bf11cce29b8c27cc1d5fe397e4e#diff-87b56e4ecbeb26b417f05dd5b64b2e7b :)

**Comment by mcinelli61** [comment]
Close #50
