### ISSUE TITLE
Bug with entry_prog crashed game

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#56]
I had two progs set so that when a particular mob wanders, it has a chance to either backstab or steal from players in the room PROVIDED there are players in the room at all.  These two progs threw constant errors and eventually crashed the game.  Maybe I'm doing something wrong, but as I understand it, if the "if" check fails here, nothing should happen at all. 

if ispc($n)
pocket $n
hide

if ispc($n)
backstab $n
hide

/(world) translate_value: Mob: 30037 invalid target in mobprog 

Edit:  Oh christ, it's because $n (trigger event) in this case is the mob itself wandering into a new room, isn't it?  Anyway, this eventually crashes the game as the mob endlessly tries to backstab and/or steal from itself.

**Comment by urizen-source** [comment]
Should be fixed by the loop protection
