### ISSUE TITLE
Issue with Prog on Obj 514 Wailka's Icy Touch

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#63]
Item has a special prog that allows for user to paralyze once per-day.  Object apparently shares code with two highgarden mobs and the highgarden gate (which paralyzes player if they enter without pass).

Issue:  The message the ring gives the wearer when coming off cooldown (The ring's magical energy has recharged) is displayed when players are released by the Highgarden paralysis progs.  Furthermore, Elder added that the ring prog has been known to crash the game.

Item VNUM: 514
Room with para prog: 8751
Mob 1: 8722 tri-flower frond
Mob 2: 8720 a retch plant

**Comment by dmhenderson76** [comment]
This also affects victims of the crown of thorns who see "The ring's magical energy has been recharged" when the prog releases them

**Comment by dmhenderson76** [comment]
Still an issue unless anyone has fixed this and just didn't close the ticket.

**Comment by TehDreadPirateRoberts** [comment]
Change para affect wear off message so it kinda works for both ring and crown.
Can't really change it to work separately for the 2 items since it is the removal of an affect (not an affect wearing off).
