### ISSUE TITLE
Yeqon's mob proc is broken and it used to be awesome

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#7]
See title.  

The proc still fires when he is >7000 hp but none of the class-specific behaviors trigger.

**Comment by urizen-source** [comment]
Tested some locally, it tried to make my testchar do stuff, is that the part you mean? 

the fallen angel Yeqon's maul POUNDS THE FUCK out of you!
the fallen angel Yeqon's maul POUNDS THE FUCK out of you!
the fallen angel Yeqon's maul POUNDS THE FUCK out of you!
the fallen angel Yeqon's maul FUCKING DEMOLISHES you!
the fallen angel Yeqon's maul POUNDS THE FUCK out of you!
Yeqon's voice echoes insidiously in your head....
A powerful compulsion overtakes your feeble intellect and controls your actions!
Your slash hits the fallen angel Yeqon very hard.
You are enveloped in flames from the fallen angel Yeqon's fireshield! - OUCH!
You feel burning poison in your blood and suffer painful convulsions.

type 'help prompt'> 

You aren't skilled enough to change opponents midfight!
Your lack of knowledge is stunning...

**Comment by dmhenderson76** [comment]
Yes, that's it - on the live port the possession proc does not work.  You see the room emote but it does not execute the possession proc at all.

**Comment by dmhenderson76** [comment]
Still valid

**Comment by TehDreadPirateRoberts** [comment]
Fixed. Prog #3 on yeqon had:
if $i,tempclass.temp
replaced it with:
if tempvar($i[tempclass])
