### ISSUE TITLE
Identify spell doesn't work on NPCs

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#72]
When you cast identify on a NPC the result is the final else, "You learn nothing new.".

**Comment by mcinelli61** [comment]
That's how it's been for as long as I've played the game,

**Comment by TehDreadPirateRoberts** [comment]
But the code has this:
 else {       /* victim */

	 if (!IS_NPC(victim)) {
		sprintf(buf,"%d Years,  %d Months,  %d Days,  %d Hours old.\n\r",
	  age(victim).year, age(victim).month,
	  age(victim).day, age(victim).hours);
		send_to_char(buf,ch);


		  sprintf(buf,"Race: ");
		  sprinttype(victim->race,race_types, buf2);
		 strcat(buf, buf2);
			 send_to_char(buf, ch);

		sprintf(buf,"   Height %dcm  Weight %dpounds \n\r",
	  GET_HEIGHT(victim), GET_WEIGHT(victim));
		send_to_char(buf,ch);

  if (GET_LEVEL(victim) > 9) {

  sprintf(buf,"Str%d,  Int %d,  Wis %d,  Dex %d,  Con %d\n\r",
  GET_STR(victim),
  GET_INT(victim),
  GET_WIS(victim),
  GET_DEX(victim),
  GET_CON(victim) );
  send_to_char(buf,ch);
}

**Comment by bdunavant** [comment]
`if (!IS_NPC(victim))` means it's for players.  You can get info on people if you cast identify on other players.  You cannot on mobs because you aren't supposed to be able to get that much detail about the monsters.  This is not a bug.

**Comment by TehDreadPirateRoberts** [comment]
Oh snap! I am a noob. Thanks for clarifying heh.
