### ISSUE TITLE
What is wrong with the Icestorm code?

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#74]
**Your voice raises to a crescendo as you call forth nature's icy wrath to engulf your enemies, dealing 233 damage!
You feel a BLAST of cold air.**

**LONG STORY SHORT:  We believe it's the damage message that's wrong, not the actual damage dealt**

1) There are no mobs or other players in the room so why am I getting a damage value?  If no damage is being dealt to anything in the room, I shouldn't see a damage number, right?

2) Why are the damage values flat?  There is no variance in damage numbers at all.  Both earthquake and firestorm vary and act like all other spells (despite the fact that they are also both AoE)

3) These damage numbers the spell is spitting out can't be factoring in resists since they are giving them up-front.  I tried removing all of my equipment, casting the spell and then putting it back on again and the damage number remains the same.  Are these numbers even real?

**Comment by dmhenderson76** [comment]
Ok yeah, I am pretty sure this broken needs to be fixed - here's what the code says:

dam = 25+learned*4; (magic.cpp starts at 12165)

1) This is the big druid 50+ skill and it doesn't even factor in spelldam (This turned out to be false - it's the message that's wrong)

2) Does not factor in victim resists or give accurate damage messages back to the druid.  Does not tell druid if the spell is resisted (since maybe it can't be?  I dunno).  Damage type is ice so it should be resistable but the messages themselves do not change. 

3) No varied damage?  Literally every other spell in the game deals varied damage.  This is the ONLY one I know of that still deals a static amount (ala DC 1.0) - but like I said, I suspect these damage messages may just be fake.

**Comment by dmhenderson76** [comment]
Did some testing with Westley and what we found is that the displayed damage message is consistently lower than the damage the victim receives, however, the damage is not equal to displayed message + spelldam, nor is it equal to displayed message + spelldam - saves.  Shouldn't one of those two scenarios be the case?  Not entirely sure - a bit fuzzy on mechanics here.

Edit:  Ok the damage calculation DOES factor in SD etc, it's just the message that's incorrect (calculation occurs in fight.cpp).

**Comment by TehDreadPirateRoberts** [comment]
Basically it was written to give you a damage message before all the damage is even calculated. It needs to be rewritten like firestorm... that would prolly be the easiest thing imo.

**Comment by dmhenderson76** [comment]
(but earthquake and firestorm exist - why not copy that code, change the damage type and damage calculation?  I'm baffled as to what happened here.)

**Comment by dmhenderson76** [comment]
Still an issue - remains open

**Comment by TehDreadPirateRoberts** [comment]
This has now been fixed!
