### ISSUE TITLE
Manipulating brewed druid potions is a mess and some just don't work at all

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#75]
**Issue: Brewed potions have incredibly screwy keywords that are difficult to manipulate in inventory.**  Brewed potions have 3 descriptors: 
(bottle type) (liquid type) (herb).  For some reason, only the first two descriptors work as keywords.  

Ex: A superior strong crystalline potion - only "superior" and "strong" will work as keywords, crystalline does not.  This sucks for multiple reasons:
  A) Brewed potions stack with empty bottles of the same type making it very hard to separate the two
  B) A druid is far more likely to be carrying spare bottles or liquid than herbs

**Proposed solution:** The druids are making the potions themselves.  Can we assume they use sticky notes to label their potions or something?  These potions should be labeled what they are, not just a string of descriptors.  "A potion of clarity" is far easier to manipulate than "A superior salty fuschia potion" (where fuschia isn't even a keyword).  Also make it so brewed potions will not stack with empty bottles of the same type else they can end up invisible in inventory or in a vault.

I get that a random adventurer stumbling across a potion in a chest somewhere might describe it as "A foul smelling brown potion", but the druid is making these things in a backyard still.  They know what they're making - why not just label them as such?  If we want to differentiate further, call them "A brewed <x> potion" so people can tell the difference between brewed and game-loaded potions.

**Comment by dmhenderson76** [comment]
Also please leave "brownt" alone and don't fix it.  It is my new favorite word:

"I see a red door and I want to paint it brownt"
"No colors anymore I want them to turn brownt"

**Comment by dmhenderson76** [comment]
Another issue with druid potions - some of them just plain don't work/do anything.  They identify with the intended effect, but quaffing them does nothing at all.  So far I have found:

Frostshield potions IDs as frostshield, do nothing when quaffed - same goes for -
Know Alignment
Stability
Solidity

Can these be fixed please?

**Comment by dmhenderson76** [comment]
Both issues outlined in this ticket are still valid.

**Comment by dmhenderson76** [comment]
Know alignment, stability and solidity are now fixed.  Still have the issue with bottles/names.  Would also like to reduce bottle size to 1lb instead of 3lbs.

**Comment by TehDreadPirateRoberts** [comment]
> Know alignment, stability and solidity are now fixed. Still have the issue with bottles/names. Would also like to reduce bottle size to 1lb instead of 3lbs.

Weight has been modified.

**Comment by TehDreadPirateRoberts** [comment]
Remaining issues can be addressed with #180
