### ISSUE TITLE
Ghaerad Spelling Error Fixes

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#80]
https://github.com/DarkCastleMUD/DarkCastle/blob/9d4c703b3afa97499f50fb96837fd1510180d830/src/obj_proc.cpp#L3284
Should be: And I'm back! Couldn't live without me eh?

https://github.com/DarkCastleMUD/DarkCastle/blob/9d4c703b3afa97499f50fb96837fd1510180d830/src/obj_proc.cpp#L3288
Should be: Fine, I will keep quiet for a while, but you will miss me!

**Comment by dmhenderson76** [comment]
Julian fixed this last night.  This can be closed.
