### ISSUE TITLE
Drown bingo fires after charmie join.  This ends up looking...weird

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#82]
Ok.
a glimmer of light chokes as briny water fills its lungs, causing 384 damage! **<-- Drown cast here**
a crackling lightning elemental joins you in the fight!
a crackling lightning elemental's bolt of energy eviscerates a glimmer of light dealing 119 damage!
a crackling lightning elemental's bolt of energy eviscerates a glimmer of light delivering 118 damage!
a crackling lightning elemental's bolt of energy eviscerates a glimmer of light dealing 121 damage!
a crackling lightning elemental's bolt of energy eviscerates a glimmer of light dealing 122 damage!
a glimmer of light is torn apart by the force of your watery blast and killed instantly!
Your surge of water drowns a glimmer of light under its crushing weight of 1417 damage! **<-- Bingo hits here**
a glimmer of light is DEAD!!
You receive 528000 exps of 555500 total.
Your blood freezes as you hear a glimmer of light's death cry.

Not a huge issue or anything, just looks goofy as hell.

**Comment by dmhenderson76** [comment]
Still valid

**Comment by TehDreadPirateRoberts** [comment]
I set drown bingo to 100% and can't recreate it. It will happen occasionally because drown bingo first casts a drown and then does the bingo after it (so mob is hit by 2x lines of damage). Sometimes the charmie might join right after first part is cast, other times it won't... I think we leave it.
