### ISSUE TITLE
Spelling...

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#86]
https://github.com/DarkCastleMUD/DarkCastle/blob/8fd8304eec644ed760c9150a4fe0c0f095676d01/src/new_edit.cpp#L71

Should be formatted not formarted...

**Comment by dmhenderson76** [comment]
Hey buddy, go formart yourself

**Comment by jhhudso** [comment]
Fixed, will be in next reboot.
