### ISSUE TITLE
//(bug) will_screwup_worn_sizes:

### ISSUE THREAD

**Issue by jhhudso** [DarkCastleMUD/DarkCastle#9]
//(bug) will_screwup_worn_sizes: knight undead corpse height 198 by 12 = 210 
//(bug) will_screwup_worn_sizes: knight undead corpse height 210 by -12 = 198 

This bug is seen constantly. We need to research root cause and fix.

**Comment by mcinelli61** [comment]
These messages come up every time a player or charmie adds or removes a
piece of eq that affects CHAR_HEIGHT. It doesn’t seem to be an actual bug.

**Comment by TehDreadPirateRoberts** [comment]
This was fixed in Sept of 2020 by Urizen.
