### ISSUE TITLE
Major crash bug - looks to be releated to the leaderboard

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#91]
Calling the leaderboard too many times will result in crashing the game which is unsurprising because...

[Leaderboard hosed.txt](https://github.com/DarkCastleMUD/DarkCastle/files/5263192/Leaderboard.hosed.txt)

**Comment by mcinelli61** [comment]
The leaderboard.txt file on the server was horribly corrupted for some
reason.  I deleted it and that took care of the crashes.
