### ISSUE TITLE
Zonefile issue - exit will not stay after crash or reboot

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#92]
No clue on this one:

There's a connection north to room 365 from from 1584.  On crash/reboot the north exit goes away - south exit remains.
Happens every single reboot and I can zsave/rsave on both sides and for some reason, the north exit just will not stay.

**Comment by jhhudso** [comment]
Fixed. There were two sets of room files which contained the same room VNUM

01500-1549.txt
and
01550-1599.txt

They both contained vnum 1583 but when you ran rsave it saved to the first file but the second file during boot overrode the first file so the change did not seem to persist. I've moved all the VNUMS > 1549 out of 01500-1549.txt and into 01550-1599.txt
